routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');




Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function (){

Route::get('dashboard','DashboardController@index')->name('dashboard');


Route::resource('allusers','AllusersController');


});


Route::group(['as'=>'user.','prefix'=>'user','namespace'=>'User','middleware'=>['auth','user']], function (){



    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('sendmoney','TrxController');
    Route::get('money','TrxController@index');
    Route::get('send','DashboardController@send')->name('send');

    //Profile
    Route::resource('profile','profileController');


    //Verify user
    Route::get('email-verify','DashboardController@emailv')->name('emailv');
    Route::get('mobile-verify','DashboardController@mobilev')->name('mobilev');
    Route::get('doc-verify','DashboardController@docv')->name('docv');





});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'email', 'password','money', 'mobile', 'dob', 'address', 'emailV', 'mobileV', 'docV', 'profile' ,'block', 'code', 'image', 'profile'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



    public function role()
    {
    return $this->belongsTo('App\Role');
    }

    public function trxs()
    {
        return $this->hasMany(trx::class);
    }

}

app/Http/Controllers/User/ChargesController.php
<?php

namespace App\Http\Controllers;

use App\charges;
use Illuminate\Http\Request;

class ChargesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function show(charges $charges)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function edit(charges $charges)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, charges $charges)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function destroy(charges $charges)
    {
        //
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\trx;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {

      if (Auth::user()->profile == 0){

          return redirect()->route('user.profile.index');

      }else {
            $users = User::all();
            $trx = trx::latest()->get();

            return view('user.dashboard', compact('users', 'trx'));

       }
    }


    public function send()

    {
        if (Auth::user()->profile == 0){

            return redirect()->route('user.profile.index');

        }else {

            return view('user.send_money');
        }
    }


    public function emailv()

    {


        return view('user.verify.emailverify');


    }


    public function mobilev(Request $request)

    {

        return 'mobilev';
    }

    public function docv(Request $request)

    {

        return 'docv';
    }
}

app/Http/Controllers/User/TrxController.php
<?php /** @noinspection ALL */

namespace App\Http\Controllers\User;

use App\charges;
use App\sendMinMax;
use App\trx;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Response;
use App\Help\helpers;


class TrxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $money = Auth::user()->money;
       if ($money >0) {
           return round($money, 2);
       }else{
           return 0;
       }

    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request,[
            'sendto'=> 'required|email',
          'amount'=> 'required|integer',

       ]);

        $minmax = sendMinMax::all();
        foreach ($minmax as $minx)
        $usee = User::where('email',$request->sendto)->get();
        foreach ($usee as $user)





                $tex = new trx;


                $amup = User::find(Auth::user()->id);

                //Send Form  Money Update User Start
                $costt = charges::all();
                foreach ($costt as $cost)
                    $parsen = $cost->cost / 100;
                $totalcost = $request->amount * $parsen;
                $total = $totalcost + $request->amount;


                if ($amup->money < $total) {
                    Toastr::warning('Your Balance is Low', 'Balance');
                    return redirect()->back();

                } elseif ($request->amount < $minx->min) {

                    Toastr::warning('You Payment Send Mimimum $' . $minx->min, 'Payment');
                    return redirect()->back();

                } elseif ($request->amount > $minx->max) {

                    Toastr::warning('You Payment Send Maximum $' . $minx->max, 'Payment');
                    return redirect()->back();

                } else {

                    $moneyup = $amup->money - $total;

                    $amup->money = $moneyup;

                    // End Money Update User End
                    $tex->user_id = Auth::user()->id;


                    $tex->amount = $request->amount;
                    $tex->charge = round($totalcost, 2);
                    $tex->via = 1;
                    $tex->refund = 1;
                    $tex->re_id = $user->id;
                    $tex->send_id = Auth::user()->id;
                    $ren = $tex->trx_id = RandomString();
                    $tex->date = time();
                    $tex->mass = $request->mass;
                    $user->money = $user->money + $request->amount;


                }

                if ($amup->save() && $user->save() && $tex->save()) {

                    Toastr::success('Your Payment Send $' . $request->amount, 'Payment');
                    return redirect()->route('user.dashboard');
                }


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function show(trx $trx)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function edit(trx $trx)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function destroy(trx $trx)
    {
        //
    }
}

app/Http/Controllers/User/VerifyDocsController.php
<?php

namespace App\Http\Controllers;

use App\verify_docs;
use Illuminate\Http\Request;

class VerifyDocsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function show(verify_docs $verify_docs)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function edit(verify_docs $verify_docs)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, verify_docs $verify_docs)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function destroy(verify_docs $verify_docs)
    {
        //
    }
}

app/Http/Controllers/User/profileController.php
<?php

namespace App\Http\Controllers\User;

use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class profileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.profile');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $profile = User::find(Auth::user()->id);


        $profile->dob = $request->dob;
        $profile->pin = $request->pin;
        $profile->mobile = $request->mobile;
        $profile->address = $request->address;
        $profile->cun = $request->cun;
        $profile->gendar = $request->gendar;

        if ($profile->save()){
            $profile->profile = '1';
            $profile->save();
            Toastr::success('Your Profile Update Success', 'Success');
            return redirect()->route('user.dashboard');
        }else{
            Toastr::error('Your Profile Not Update', 'Error');
            return redirect()->route('user.dashboard');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/dashboard.blade.php

@extends('layouts.users.master')

@section('title', 'Dashboard')

@push('css')

@endpush


@section('content')






        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="page-content-inner">



            <div class="card">
                <div class="header"> <h3>RECENT TRANSACTIONS</h3></div>
            <div class="portlet box blue panel-success" style="padding-top: 15px;">
                 <div class="portlet-title">
                    <div class="caption">

                        <i class="fa fa-list"></i>  </div>
                </div>

                <div class="portlet-body">
                    <div class="panel-group accordion" id="accordion1">












               <?php
                         $sds =  $trx->where('send_id',Auth::user()->id);
                            foreach ($sds->take(5) as $row){


                     if($row->send_id > 0){
                       $sig = "-";
                       $amo = round($row->amount+$row->charge, 2);
                       $free = $row->charge;
                       $paytxt = "Sent To";
                       $printrefund = "";
                       $color = "panel-danger";
                       $name = $users->find($row->re_id)->name;
                       $email = $users->find($row->re_id)->email;
                       $hed = 'Payment Send To ';

                       }else{

                     }


                      if ($row->mass == ''){
                         $mass = '';
                      }else{

                         $mass = "Message: $row->mass";
                      }
                      ?>








                                <div class="panel {{ $color }}">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">

                                            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#{{$row->id}}" aria-expanded="false">




                                                <div class="row">

                                                    <div class="col-xs-2 col-md-2">
                                                        <b style="font-size: 14px;">{{date('d M',$row->date)}}</b></div>

                                                    <div class="col-xs-10 col-md-8"><b> {{ $hed }}  {{ $name }}</b><br> </div>


                                                    <div class="col-xs-6 col-md-2 pull-right">

                                                        <b style="font-size: 20px;">{{ $sig }} </b> <b style="font-size: 14px;">${{round($row->amount),2}}</b>
                                                    </div>


                                                </div>


                                            </a>
                                        </h4>
                                    </div>
                                    <div id="{{$row->id}}" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="panel-body">



                                            <div class="row">
                                                <div class="col-md-11 col-md-offset-1 col-sm-12">

                                                    <div class="col-md-4 col-sm-12">
                                                        <h4 style="font-weight: bold;">{{ $paytxt }}</h4>
                                                        <p class="lead" style="font-size: 15px;">{{ $name }}<br>
                                                            <a href="mailto:{{ $email }}" style="font-size: 12px;">{{ $email }}</a></p>
                                                    </div>


                                                    <div class="col-md-4 col-sm-12">
                                                        <h4 style="font-weight: bold;">Transaction ID</h4>
                                                        <p class="lead" style="margin-bottom: 5px; font-size: 15px;">{{$row->trx_id}}</p>

                                                        <i class="fa fa-calendar"></i> <br class="uppercase">  {{date('d M Y',$row->date)}}<br>{{date('H:i:s D T',$row->date)}}
                                                        </br> {{$date = new ago_time(date('Y-m-d',$row->date))}}
                                                        </b>

                                                    </div>


                                                    <div class="col-md-4 col-sm-12">
                                                        <h4 style="font-weight: bold;">Details</h4>

                                                        <div class="col-xs-12">
                                                          <span class="pull-right">{{round($row->amount),2}} USD</span>  <br>

                                                        </div>
                                                        <div class="col-xs-12">
                                                            Fee  <span class="pull-right">{{ $free }} USD</span>  <br> </div>
                                                        <hr>
                                                        <div class="col-xs-12">
                                                            <p><b >=<span class="pull-right">{{ $amo }} USD</span>  </b></p>
                                                        </div>
                                                        <p></p>


                                                    </div>

                                                    <div class="col-md-12">

                                                      {{ $mass }}


                                                </div>

                                            </div><!-- row -->



                                        </div>
                                    </div>
                                </div>

                                </div>








                   <?php
                       }

                   $sds =  $trx->where('re_id',Auth::user()->id);
                   foreach ($sds->take(5) as $row){


                   if($row->send_id > 0){
                       $sig = "+";
                       $amo = round($row->amount, 2);
                       $free = 0;
                       $paytxt = "Paid By";
                       $printrefund = "REFUND";
                       $color = "panel-success";
                       $name = $users->find($row->send_id)->name;
                       $email = $users->find($row->send_id)->email;
                       $hed = 'Payment Received Via ';

                   }else{

                   }


                   if ($row->mass == ''){
                       $mass = '';
                   }else{

                       $mass = "Message: $row->mass";
                   }
                   ?>








                   <div class="panel {{ $color }}">
                       <div class="panel-heading">
                           <h4 class="panel-title">

                               <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#{{$row->id}}" aria-expanded="false">




                                   <div class="row">

                                       <div class="col-xs-2 col-md-2">
                                           <b style="font-size: 14px;">{{date('d M',$row->date)}}</b></div>

                                       <div class="col-xs-10 col-md-8"><b> {{ $hed }}  {{ $name }}</b><br> </div>


                                       <div class="col-xs-6 col-md-2 pull-right">

                                           <b style="font-size: 18px;">{{ $sig }}</b> <b style="font-size: 14px;">${{round($row->amount),2}}</b>
                                       </div>


                                   </div>


                               </a>
                           </h4>
                       </div>
                       <div id="{{$row->id}}" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                           <div class="panel-body">



                               <div class="row">
                                   <div class="col-md-11 col-md-offset-1 col-sm-12">

                                       <div class="col-md-4 col-sm-12">
                                           <h4 style="font-weight: bold;">{{ $paytxt }}</h4>
                                           <p class="lead" style="font-size: 15px;">{{ $name }}<br>
                                               <a href="mailto:{{ $email }}" style="font-size: 12px;">{{ $email }}</a></p>
                                       </div>


                                       <div class="col-md-4 col-sm-12">
                                           <h4 style="font-weight: bold;">Transaction ID</h4>
                                           <p class="lead" style="margin-bottom: 5px; font-size: 15px;">{{$row->trx_id}}</p>

                                           <i class="fa fa-calendar"></i> <br class="uppercase">  {{date('d M Y',$row->date)}}<br>{{date('H:i:s D T',$row->date)}}
                                           </br> {{$date = new ago_time(date('Y-m-d',$row->date))}}
                                           </b>

                                       </div>


                                       <div class="col-md-4 col-sm-12">
                                           <h4 style="font-weight: bold;">Details</h4>

                                           <div class="col-xs-12">
                                               <span class="pull-right">{{round($row->amount),2}} USD</span>  <br>

                                           </div>
                                           <div class="col-xs-12">
                                               Fee  <span class="pull-right">{{ $free }} USD</span>  <br> </div>
                                           <hr>
                                           <div class="col-xs-12">
                                               <p><b >=<span class="pull-right">{{ $amo }} USD</span>  </b></p>
                                           </div>
                                           <p></p>


                                       </div>

                                       <div class="col-md-12">

                                           {{ $mass }}


                                       </div>

                                   </div><!-- row -->



                               </div>
                           </div>
                       </div>

                   </div>





                   <?php  }?>



                    </div>
                </div>

            </div>



        </div>
           <a href=""><h3> VIEW ALL TRANSACTIONS </h3></a>

    </div>





@endsection


@push('js')

@endpush

resources/views/user/send_money.blade.php
@extends('layouts.users.master')

@section('title', 'Send Money')

@push('css')

@endpush


@section('content')

    <div style="padding-top: 30px;"></div>

    <div class="col-md-12 col-sm-12 col-lg-12">
<form action="{{route('user.sendmoney.store')}}" method="post">
    @csrf


    <div class="form-group input-group">
        <span class="input-group-addon">To</span>
        <input type="text" class="form-control" placeholder="Type Email" id="sendto" name="sendto">
    </div>

    <br>


    <div id="dt"></div>
    <div id="dts"></div>



    <div class="form-group input-group" >
        <span class="input-group-addon">$</span>
        <input type="text" class="form-control" placeholder="Amount USD" name="amount" id="am">
        <span class="input-group-addon">USD</span>
    </div>
    <div id="cp" style="color: red;"></div>

    <br>
    <textarea class="form-control" rows="5" name="mass" placeholder="Your Message (Optional)"></textarea>
    <br>
    <input type="submit" value="Send" class="btn btn-success btn-block">




</form>
    </div>

@endsection


@push('js')


    <script>




        jQuery(document).ready(function(){


            $("#cclick").click(function(){

                $("#cp").show();


                $("#charge").val("1");

                $("#cclick").hide();
                $("#cclick2").show();

            });



            $("#cclick2").click(function(){

                $("#cp").hide();
                $("#charge").val("0");

                $("#cclick2").hide();
                $("#cclick").show();

            });


            $("#cclick").click(function(){

                var amm = $("#am").val();

                $.post(
                    "jsapi-charge.php",
                    {
                        amount : amm
                    },
                    function(data) {
                        $("#cp").html(data);
                    }
                );

            });


            $("#am").on('input',function(){

                var amm = $("#am").val();

                $.post(
                    "jsapi-charge.php",
                    {
                        amount : amm
                    },
                    function(data) {
                        $("#cp").html(data);
                    }
                );

            });


            $("#dt").click(function(){
                $("#sendto").fadeOut("500");
                $("#dt").fadeOut("1000",function() {
                    $("#amountt").fadeIn("1000");
                });
            });


            $('#sendto').on('input', function() {
                var dt = $("#sendto").val();
                $.post(
                    "<?php echo url('user/usr');?>",
                    {
                        dt : dt,
                        data:'_token = <?php echo csrf_token() ?>',
                    },
                    function(data) {
                        var result = $.trim(data);
                        if(result==="data"){
                            $("#dt").hide();
                            $("#dts").show();
                            $("#dts").html("NO USER FOUND WITH THIS EMAIL");
                        } else {
                            $("#dt").show();
                            $("#dts").hide();
                            $("#dt").html(data);
                        }



                    }
                );


            });


        });
    </script>

@endpush