routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');




Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth','admin']], function (){

Route::get('dashboard','DashboardController@index')->name('dashboard');


Route::resource('allusers','AllusersController');


});


Route::group(['as'=>'user.','prefix'=>'user','namespace'=>'User','middleware'=>['auth','user']], function (){



    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('sendmoney','TrxController');
    Route::get('money','TrxController@index');
    Route::get('send','DashboardController@send')->name('send');

    //Profile
    Route::resource('profile','profileController');


    //Verify user
    Route::get('email-verify','DashboardController@emailv')->name('emailv');
    Route::get('mobile-verify','DashboardController@mobilev')->name('mobilev');
    Route::get('doc-verify','DashboardController@docv')->name('docv');





});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'email', 'password','money', 'mobile', 'dob', 'address', 'emailV', 'mobileV', 'docV', 'profile' ,'block', 'code', 'image', 'profile'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



    public function role()
    {
    return $this->belongsTo('App\Role');
    }

    public function trxs()
    {
        return $this->hasMany(trx::class);
    }

}

app/Http/Controllers/User/ChargesController.php
<?php

namespace App\Http\Controllers;

use App\charges;
use Illuminate\Http\Request;

class ChargesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function show(charges $charges)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function edit(charges $charges)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, charges $charges)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\charges  $charges
     * @return \Illuminate\Http\Response
     */
    public function destroy(charges $charges)
    {
        //
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\trx;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {

      if (Auth::user()->profile == 0){

          return redirect()->route('user.profile.index');

      }else {
            $users = User::all();
            $trx = trx::latest()->get();

            return view('user.dashboard', compact('users', 'trx'));

       }
    }


    public function send()

    {
        if (Auth::user()->profile == 0){

            return redirect()->route('user.profile.index');

        }else {

            return view('user.send_money');
        }
    }


    public function emailv()

    {


        return view('user.verify.emailverify');


    }


    public function mobilev(Request $request)

    {

        return 'mobilev';
    }

    public function docv(Request $request)

    {

        return 'docv';
    }
}

app/Http/Controllers/User/TrxController.php
<?php /** @noinspection ALL */

namespace App\Http\Controllers\User;

use App\charges;
use App\sendMinMax;
use App\trx;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Response;
use App\Help\helpers;


class TrxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $money = Auth::user()->money;
       if ($money >0) {
           return round($money, 2);
       }else{
           return 0;
       }

    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request,[
            'sendto'=> 'required|email',
          'amount'=> 'required|integer',

       ]);

        $minmax = sendMinMax::all();
        foreach ($minmax as $minx)
        $usee = User::where('email',$request->sendto)->get();
        foreach ($usee as $user)





                $tex = new trx;


                $amup = User::find(Auth::user()->id);

                //Send Form  Money Update User Start
                $costt = charges::all();
                foreach ($costt as $cost)
                    $parsen = $cost->cost / 100;
                $totalcost = $request->amount * $parsen;
                $total = $totalcost + $request->amount;


                if ($amup->money < $total) {
                    Toastr::warning('Your Balance is Low', 'Balance');
                    return redirect()->back();

                } elseif ($request->amount < $minx->min) {

                    Toastr::warning('You Payment Send Mimimum $' . $minx->min, 'Payment');
                    return redirect()->back();

                } elseif ($request->amount > $minx->max) {

                    Toastr::warning('You Payment Send Maximum $' . $minx->max, 'Payment');
                    return redirect()->back();

                } else {

                    $moneyup = $amup->money - $total;

                    $amup->money = $moneyup;

                    // End Money Update User End
                    $tex->user_id = Auth::user()->id;


                    $tex->amount = $request->amount;
                    $tex->charge = round($totalcost, 2);
                    $tex->via = 1;
                    $tex->refund = 1;
                    $tex->re_id = $user->id;
                    $tex->send_id = Auth::user()->id;
                    $ren = $tex->trx_id = RandomString();
                    $tex->date = time();
                    $tex->mass = $request->mass;
                    $user->money = $user->money + $request->amount;


                }

                if ($amup->save() && $user->save() && $tex->save()) {

                    Toastr::success('Your Payment Send $' . $request->amount, 'Payment');
                    return redirect()->route('user.dashboard');
                }


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function show(trx $trx)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function edit(trx $trx)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\trx  $trx
     * @return \Illuminate\Http\Response
     */
    public function destroy(trx $trx)
    {
        //
    }
}

app/Http/Controllers/User/VerifyDocsController.php
<?php

namespace App\Http\Controllers;

use App\verify_docs;
use Illuminate\Http\Request;

class VerifyDocsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function show(verify_docs $verify_docs)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function edit(verify_docs $verify_docs)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, verify_docs $verify_docs)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\verify_docs  $verify_docs
     * @return \Illuminate\Http\Response
     */
    public function destroy(verify_docs $verify_docs)
    {
        //
    }
}

app/Http/Controllers/User/profileController.php
<?php

namespace App\Http\Controllers\User;

use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class profileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.profile');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $profile = User::find(Auth::user()->id);


        $profile->dob = $request->dob;
        $profile->pin = $request->pin;
        $profile->mobile = $request->mobile;
        $profile->address = $request->address;
        $profile->cun = $request->cun;
        $profile->gendar = $request->gendar;

        if ($profile->save()){
            $profile->profile = '1';
            $profile->save();
            Toastr::success('Your Profile Update Success', 'Success');
            return redirect()->route('user.dashboard');
        }else{
            Toastr::error('Your Profile Not Update', 'Error');
            return redirect()->route('user.dashboard');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/user/master.blade.php
<html lang="{{app()->getLocale()}}">

<head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="csrf-token" content="{{csrf_token()}}">

    <title>@yield('title') - {{ config('app.name', 'Laravel')}}</title>



    <!-- GLOBAL STYLES -->
    <!-- GLOBAL STYLES -->
    <link rel="stylesheet" href="{{asset('assets/plugins/bootstrap/css/bootstrap.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/css/main.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/css/theme.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/css/MoneAdmin.css')}}" />
    <link rel="stylesheet" href="{{asset('assets/plugins/Font-Awesome/css/font-awesome.css')}}" />
    <!--END GLOBAL STYLES -->

    <!-- PAGE LEVEL STYLES -->
    <link href="{{asset('assets/css/layout2.css')}}" rel="stylesheet" />
    <!-- END PAGE LEVEL  STYLES -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="https://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">

@stack('css')

</head>

<body class="padTop53">




<script>
    var Auto_refresh = setInterval(function () {
        $('#dd').load('<?php echo url('user/money');?>').fadeIn("slow");
    },1000);

    var Auto_refresh2 = setInterval(function () {
        $('#ddd').load('<?php echo url('user/money');?>').fadeIn("slow");
    },1000);



</script>


<!-- MAIN WRAPPER -->
<div id="wrap">


    <!-- HEADER SECTION -->
    <div id="top">

        @include('layouts.user.topbar')

    </div>
    <!-- END HEADER SECTION -->



    <!-- MENU SECTION -->
    <div id="left">
        <div class="media user-media well-small">
            <a class="user-link" href="#">
                <img class="media-object img-thumbnail user-img" alt="User Picture" src="{{asset('assets/img/user.gif')}}" />
            </a>
            <br />
            <div class="media-body">
                <h5 class="media-heading"> {{ Auth::user()->name }}</h5>
                <ul class="list-unstyled user-info">

                    <li >
                       <h4 class="panel-success text-center">Balance $<b id="dd"></b></h4>


                    </li>

                </ul>
            </div>
            <br />
        </div>

       @include('layouts.user.sidebar')

    </div>
    <!--END MENU SECTION -->


    <!--PAGE CONTENT -->
    <div id="content">

        @yield('content')




    </div>
    <!--END PAGE CONTENT -->
    <!-- RIGHT STRIP  SECTION -->
    <div id="right">


        <div class="well well-small">
            <ul class="list-unstyled">
                <li>Balance &nbsp;&nbsp;&nbsp; : <span>$<b id="ddd"></b></span></li>
                <li>Account ID &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;: <span>53,000</span></li>
                <li>Account status   : <span>3,000</span></li>
                <li>Account type &nbsp;&nbsp;: <span>3,000</span></li>
                <li>Your Login ip &nbsp;&nbsp;: <span>3,000</span></li>
            </ul>
        </div>
        <div class="well well-small">
            <button class="btn btn-block"> Help </button>
            <button class="btn btn-primary btn-block"> Tickets</button>
            <button class="btn btn-info btn-block"> New </button>
            <button class="btn btn-success btn-block"> Users </button>
            <button class="btn btn-danger btn-block"> Profit </button>
            <button class="btn btn-warning btn-block"> Sales </button>
            <button class="btn btn-inverse btn-block"> Stock </button>
        </div>
        <div class="well well-small">
            <span>Profit</span><span class="pull-right"><small>20%</small></span>

            <div class="progress mini">
                <div class="progress-bar progress-bar-info" style="width: 20%"></div>
            </div>
            <span>Sales</span><span class="pull-right"><small>40%</small></span>

            <div class="progress mini">
                <div class="progress-bar progress-bar-success" style="width: 40%"></div>
            </div>
            <span>Pending</span><span class="pull-right"><small>60%</small></span>

            <div class="progress mini">
                <div class="progress-bar progress-bar-warning" style="width: 60%"></div>
            </div>
            <span>Summary</span><span class="pull-right"><small>80%</small></span>

            <div class="progress mini">
                <div class="progress-bar progress-bar-danger" style="width: 80%"></div>
            </div>
        </div>




    </div>
    <!-- END RIGHT STRIP  SECTION -->

</div>

<!--END MAIN WRAPPER -->








<!-- FOOTER -->
<div id="footer">
    <p>&copy; {{date('Y')}} E-wallet</p>
</div>
<!--END FOOTER -->










<!-- GLOBAL SCRIPTS -->
<script src="{{asset('assets/plugins/jquery-2.0.3.min.js')}}"></script>
<script src="{{asset('assets/plugins/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/plugins/modernizr-2.6.2-respond-1.1.0.min.js')}}"></script>
<!-- END GLOBAL SCRIPTS -->

<script src="https://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
{!! Toastr::message() !!}

<script>

    @if($errors->any())

        @foreach($errors->all() as $error)

             toastr.error('{{$error}}','Error',{
                 closeButton:true,
        progressBar:true,
    });
             @endforeach
    @endif

</script>

@stack('js')

</body>


</html>

resources/views/layouts/user/sidebar.blade.php
<ul id="menu" class="collapse">


    <li class="panel">
        <a href="{{route('user.dashboard')}}" >
            <i class="icon-table"></i> Dashboard


        </a>
    </li>




    <li><a href="{{route('user.send')}}"><i class="icon-money"></i> Send Money </a></li>
    <li><a href="tables.html"><i class="icon-table"></i> Data Tables </a></li>
    <li><a href="maps.html"><i class="icon-map-marker"></i> Maps </a></li>

    <li><a href="grid.html"><i class="icon-columns"></i> Grid </a></li>

    <li><a href="login.html"><i class="icon-signin"></i> Login Page </a></li>

</ul>

resources/views/layouts/user/topbar.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top " style="padding-top: 10px;">
    <a data-original-title="Show/Hide Menu" data-placement="bottom" data-tooltip="tooltip" class="accordion-toggle btn btn-primary btn-sm visible-xs" data-toggle="collapse" href="#menu" id="menu-toggle">
        <i class="icon-align-justify"></i>
    </a>
    <!-- LOGO SECTION -->
    <header class="navbar-header">

        <a href="index.html" class="navbar-brand">
            <img src="{{asset('assets/img/logo.png')}}" alt="" /></a>
    </header>
    <!-- END LOGO SECTION -->
    <ul class="nav navbar-top-links navbar-right">

        <!-- MESSAGES SECTION -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="label label-success">2</span>    <i class="icon-envelope-alt"></i>&nbsp; <i class="icon-chevron-down"></i>
            </a>

            <ul class="dropdown-menu dropdown-messages">
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                            <em>Today</em>
                                        </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing.
                            <br />
                            <span class="label label-primary">Important</span>

                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>Raphel Jonson</strong>
                            <span class="pull-right text-muted">
                                            <em>Yesterday</em>
                                        </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing.
                            <br />
                            <span class="label label-success"> Moderate </span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>Chi Ley Suk</strong>
                            <span class="pull-right text-muted">
                                            <em>26 Jan 2014</em>
                                        </span>
                        </div>
                        <div>Lorem ipsum dolor sit amet, consectetur adipiscing.
                            <br />
                            <span class="label label-danger"> Low </span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="icon-angle-right"></i>
                    </a>
                </li>
            </ul>

        </li>
        <!--END MESSAGES SECTION -->

        <!--TASK SECTION -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="label label-danger">5</span>   <i class="icon-tasks"></i>&nbsp; <i class="icon-chevron-down"></i>
            </a>

            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong> Profile </strong>
                                <span class="pull-right text-muted">40% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">40% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong> Pending Tasks </strong>
                                <span class="pull-right text-muted">20% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong> Work Completed </strong>
                                <span class="pull-right text-muted">60% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong> Summary </strong>
                                <span class="pull-right text-muted">80% Complete</span>
                            </p>
                            <div class="progress progress-striped active">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Tasks</strong>
                        <i class="icon-angle-right"></i>
                    </a>
                </li>
            </ul>

        </li>
        <!--END TASK SECTION -->

        <!--ALERTS SECTION -->
        <li class="chat-panel dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="label label-info">8</span>   <i class="icon-comments"></i>&nbsp; <i class="icon-chevron-down"></i>
            </a>

            <ul class="dropdown-menu dropdown-alerts">

                <li>
                    <a href="#">
                        <div>
                            <i class="icon-comment" ></i> New Comment
                            <span class="pull-right text-muted small"> 4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="icon-twitter info"></i> 3 New Follower
                            <span class="pull-right text-muted small"> 9 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="icon-envelope"></i> Message Sent
                            <span class="pull-right text-muted small" > 20 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="icon-tasks"></i> New Task
                            <span class="pull-right text-muted small"> 1 Hour ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="icon-upload"></i> Server Rebooted
                            <span class="pull-right text-muted small"> 2 Hour ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="icon-angle-right"></i>
                    </a>
                </li>
            </ul>

        </li>
        <!-- END ALERTS SECTION -->

        <!--ADMIN SETTINGS SECTIONS -->

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="icon-user "></i>&nbsp; <i class="icon-chevron-down "></i>
            </a>

            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="icon-user"></i> User Profile </a>
                </li>
                <li><a href="#"><i class="icon-gear"></i> Settings </a>
                </li>
                <li class="divider"></li>
                <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="icon-signout"></i> {{ __('Logout') }} </a>
                </li>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </ul>

        </li>
        <!--END ADMIN SETTINGS -->
    </ul>

</nav>